FROM pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel

ENV CUDA_HOME='/usr/local/cuda-11.1'
ENV TORCH_CUDA_ARCH_LIST=Ampere

RUN rm /etc/apt/sources.list.d/cuda.list \
    && rm /etc/apt/sources.list.d/nvidia-ml.list \
    && apt-key del 7fa2af80 \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt update && \
    apt install ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./clrnet /clrnet
WORKDIR /clrnet

RUN pip install --upgrade pip && \
    pip install -r requirements.txt
RUN python setup.py build develop